config:
    build_jobs: 32
    install_path_scheme: '{name}-{version}-{hash:7}'
    install_tree: $SPACK_USER_PREFIX/23.03/
    source_cache: $SPACK_USER_PREFIX/23.03/cache
    misc_cache: $SPACK_USER_PREFIX/23.03/cache
    install_missing_compilers: false
    suppress_gpg_warnings: true

