config:
  build_jobs: 32
  install_tree:
    projections:
      all: '{name}-{version}-{hash:7}'
    root: $SPACK_USER_PREFIX
  source_cache: $SPACK_USER_PREFIX/cache
  misc_cache: $SPACK_USER_PREFIX/cache
  suppress_gpg_warnings: true
